# Generated by Django 5.2 on 2025-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарий к заказу')),
                ('email', models.EmailField(max_length=254, verbose_name='Email заказчика')),
                ('file', models.FileField(upload_to='files', verbose_name='Файл заказчика')),
            ],
        ),
    ]
